[package]
name = "bfieldcodec_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2", features = ["full", "derive"]}
quote = "1.0"

[lib]
proc-macro = true

